project:
  type: website
  output-dir: docs

website:
  title: "Kaya's Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CrumpLab/quartoCourseBlog
      - icon: linkedin
        href: https://www.linkedin.com/in/kaya-jakowczuk-142b21230/?trk=public-profile-join-page
format:
  html:
    theme: lux
    css: styles.css

editor: visual

